# Data Inspection and Cleaning

In [1]:
## Load Dataset

import pandas as pd

df = pd.read_csv("Raw_Toy_Data.csv")

#### Initial Dataset Inspection

In [2]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
0,1002,Customer_2,F,20,Delhi,Laptop,Electronics,3,1274.0,UPI,2026-07-01,NaN,NaN
1,1003,Customer_3,M,21,UP,Shoes,Footwear,4,1411.0,Card,2026-07-02,NaN,NaN
2,1004,Customer_4,F,22,Maharashtra,Rice,Food,1,1548.0,Cash,2026-07-03,NaN,NaN
3,1005,Customer_5,M,23,Karnataka,Shirt,Clothing,2,NaN,NetBanking,2026-07-04,NaN,NaN
4,1006,Customer_6,F,24,Gujarat,Mixer,Home,3,1822.0,UPI,2026-07-05,NaN,NaN

In [3]:
df.tail()

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
55,1057,Customer_57,M,30,Delhi,Laptop,Electronics,2,8809.0,NetBanking,2026-07-28,NaN,NaN
56,1058,Customer_58,F,31,UP,Shoes,Footwear,3,8946.0,UPI,2026-07-01,NaN,NaN
57,1059,Customer_59,M,32,Maharashtra,Rice,Food,4,9083.0,Card,2026-07-02,NaN,NaN
58,1060,Customer_60,F,33,Karnataka,Shirt,Clothing,1,9220.0,Cash,2026-07-03,NaN,NaN
59,1061,Customer_61,M,34,Gujarat,Mixer,Home,2,9357.0,NetBanking,2026-07-04,NaN,NaN

In [4]:
df.shape

(60, 13)

In [5]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'Product',
       'Category', 'Orders', 'Amount', 'Payment_Mode', 'Order_Date', 'Status',
       'Notes'],
      dtype='object')

In [6]:
df.dtypes

Customer_ID        int64
Customer_Name     object
Gender            object
Age                int64
State             object
Product           object
Category          object
Orders             int64
Amount           float64
Payment_Mode      object
Order_Date        object
Status           float64
Notes            float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    60 non-null     int64
 1   Customer_Name  60 non-null     object
 2   Gender         59 non-null     object
 3   Age            60 non-null     int64
 4   State          59 non-null     object
 5   Product        60 non-null     object
 6   Category       60 non-null     object
 7   Orders         60 non-null     int64
 8   Amount         57 non-null     float64
 9   Payment_Mode   60 non-null     object
 10  Order_Date     60 non-null     object
 11  Status         0 non-null      float64
 12  Notes          0 non-null      float64
dtypes: float64(3), int64(3), object(7)
memory usage: 6.2+ KB

In [8]:
df.describe()

       Customer_ID        Age     Orders         Amount  Status  Notes
count    60.000000  60.000000  60.000000      57.000000     0.0    0.0
mean   1031.050000  36.750000   2.500000   22742.175439     NaN    NaN
std      17.714712  12.869126   1.127469  131775.271428     NaN    NaN
min    1002.000000  18.000000   1.000000    -500.000000     NaN    NaN
25%    1015.750000  26.000000   1.750000    3329.000000     NaN    NaN
50%    1030.500000  33.500000   2.500000    5384.000000     NaN    NaN
75%    1046.250000  47.250000   3.250000    7439.000000     NaN    NaN
max    1061.000000  62.000000   4.000000  999999.000000     NaN    NaN

#### Investigation 
* Rows : 60
* Columns : 13
* Numerical Columns : Age, Orders, Amount
* Categorical Columns : Customer_Name, Gender, State, Product, Category, Payment_Mode
* Identifier Columns : Customer_ID
* Date Columns : Order_Date
* Additional columns : Status, Notes

#### Business Understanding 
* This sales dataset contains customer demographic information and purchasing records. The objective is to clean the dataset and prepare it for business analysis.

# Data Cleaning

### Remove Unecessary Columns
* There are 2 columns which are filled with nulls and contribute nothing to our analysis
    * Status : Contains nulls only
    * notes : Contains nulls only

* Removing  both columns as they provide no analytical value.

In [9]:
df[['Status','Notes']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Status  0 non-null      float64
 1   Notes   0 non-null      float64
dtypes: float64(2)
memory usage: 1.1 KB

In [10]:
# dropping cols : status and notes

df.drop(columns=['Status','Notes'], inplace=True)

In [11]:
# Revalidating

df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'Product',
       'Category', 'Orders', 'Amount', 'Payment_Mode', 'Order_Date'],
      dtype='object')

### Identifier Columns Validation

* Identifier Columns : Customer_Id

In [12]:
# * As Customer_ID data type is int, because it represents labels not numeric values, and does not contributes to any numerical analysis

df['Customer_ID'] = df['Customer_ID'].astype(str)

In [13]:
df['Customer_ID'].dtype

dtype('O')

In [14]:
## Nulls Check

df['Customer_ID'].isnull().sum()

# No nulls in Customer_ID column

0

In [15]:
## Duplicate check

df['Customer_ID'].duplicated().sum()

# Duplicates :  2

df[df['Customer_ID'].duplicated(keep=False)]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date
8,1010,Customer_10,F,28,Karnataka,Shirt,Clothing,3,NaN,UPI,2026-07-09
10,1010,Customer_12,F,30,Delhi,Laptop,Electronics,1,2644.0,Cash,2026-07-11
33,1010,Customer_35,M,53,Karnataka,Shirt,Clothing,4,5795.0,Card,2026-07-06

In [16]:
## Dropping Duplicate Columns

df.drop_duplicates(subset=['Customer_ID'], inplace=True)

In [17]:
## Revalidation

df['Customer_ID'].duplicated().sum()

0

### Categorical Columns Validation

* Categorical cols : 
    'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'

In [18]:
# checking dtypes

categorical_cols = [
    'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
]

df[categorical_cols].dtypes

Customer_Name    object
Gender           object
State            object
Product          object
Category         object
Payment_Mode     object
dtype: object

In [19]:

# Handling nulls

categorical_cols = [
    'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
]

df[categorical_cols].isnull().sum()

Customer_Name    0
Gender           1
State            1
Product          0
Category         0
Payment_Mode     0
dtype: int64

In [20]:
df[df[['Gender','State']].isnull().any(axis=1)]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date
6,1008,Customer_8,NaN,26,UP,Shoes,Footwear,1,2096.0,Cash,2026-07-07
13,1015,Customer_15,M,33,NaN,Shirt,Clothing,4,3055.0,Card,2026-07-14

In [21]:
## Removing nulls columns

df.dropna(subset=['Gender','State'],inplace=True)

In [22]:
df[categorical_cols].isnull().sum()

Customer_Name    0
Gender           0
State            0
Product          0
Category         0
Payment_Mode     0
dtype: int64

In [23]:
## Handling Duplicates

df[categorical_cols].duplicated().sum()

## No duplicate rows

0

#### Category Validation — Consistency & Standardization

* Til now, i have removed all of the nulls and duplicates from categorical cols , let us investigate data consistency and categories.

In [24]:
categorical_cols = [
    'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
]

for col in categorical_cols:
    print(f'\n{col}')
    print(df[col].unique())

## As we can see there are data inconsistency in  2 columns
# Gender contains inconsistent labels.
# State contains spelling inconsistency.

Customer_Name
['Customer_2' 'Customer_3' 'Customer_4' 'Customer_5' 'Customer_6'
 'Customer_7' 'Customer_9' 'Customer_10' 'Customer_11' 'Customer_13'
 'Customer_14' 'Customer_16' 'Customer_17' 'Customer_18' 'Customer_19'
 'Customer_20' 'Customer_21' 'Customer_22' 'Customer_23' 'Customer_24'
 'Customer_25' 'Customer_26' 'Customer_27' 'Customer_28' 'Customer_29'
 'Customer_30' 'Customer_31' 'Customer_32' 'Customer_33' 'Customer_34'
 'Customer_36' 'Customer_37' 'Customer_38' 'Customer_39' 'Customer_40'
 'Customer_41' 'Customer_42' 'Customer_43' 'Customer_44' 'Customer_45'
 'Customer_46' 'Customer_47' 'Customer_48' 'Customer_49' 'Customer_50'
 'Customer_51' 'Customer_52' 'Customer_53' 'Customer_54' 'Customer_55'
 'Customer_56' 'Customer_57' 'Customer_58' 'Customer_59' 'Customer_60'
 'Customer_61']

Gender
['F' 'M' 'Female' 'Male']

State
['Delhi' 'UP' 'Maharashtra' 'Karnataka' 'Gujarat' 'Maharastra']

Product
['Laptop' 'Shoes' 'Rice' 'Shirt' 'Mixer']

Category
['Electronics' 'Footwear' 'Food' 'Clothing' 'Home']

Payment_Mode
['UPI' 'Card' 'Cash' 'NetBanking']

In [25]:
## CLeaning data inconsistency

df['Gender'] = df['Gender'].replace({
    'M' : 'Male',
    'F' : 'Female'
})

In [26]:
df['State'] = df['State'].replace({
    'Maharastra':'Maharashtra'
})

In [27]:
## Revalidation 

categorical_cols = [
    'Gender',
    'State'   
]

for col in categorical_cols:
    print(f'\n{col}')
    print(df[col].unique())

Gender
['Female' 'Male']

State
['Delhi' 'UP' 'Maharashtra' 'Karnataka' 'Gujarat']

# Numerical Column Validation

In [28]:
numerical_cols = ['Amount','Age','Orders']

In [29]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].info()

<class 'pandas.core.frame.DataFrame'>
Index: 56 entries, 0 to 59
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Amount  53 non-null     float64
 1   Age     56 non-null     int64
 2   Orders  56 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 1.8 KB

In [30]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].describe()

## As we can see
# Age range is reasonable [min: 18,  max: 62,  Avg: 36 ]
# Orders range is reasonable [min: 1,  max:2,  Avg: 4]
# Amount columns looks weired as min amount is in negative, and max amount is very large

              Amount        Age     Orders
count      53.000000  56.000000  56.000000
mean    24202.150943  36.839286   2.500000
std    136635.849354  13.025537   1.095445
min      -500.000000  18.000000   1.000000
25%      3603.000000  25.750000   2.000000
50%      5521.000000  34.000000   2.500000
75%      7576.000000  47.250000   3.000000
max    999999.000000  62.000000   4.000000

In [31]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].isnull().sum()

Amount    3
Age       0
Orders    0
dtype: int64

In [32]:
## Handling Nulls 

df.dropna(subset=['Amount'], inplace=True)

In [33]:
# Revalidate 

df['Amount'].isnull().sum()

0

In [34]:
## Handling duplicates
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].duplicated().sum()

## There are no duplicates

0

In [35]:
## Now validating Numerical Data for negative values 

df[df['Amount']<0]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date
38,1040,Customer_40,Female,58,Karnataka,Shirt,Clothing,1,-500.0,Cash,2026-07-11

In [36]:
## let us drop this col as it does not makes sense someone buyins a short for -500 rupees

df.drop(index=38, inplace=True)

In [37]:
## Revalidation

df[df['Amount'] < 0]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, State, Product, Category, Orders, Amount, Payment_Mode, Order_Date]
Index: []

In [38]:
## Outlier investigation , as we saw in statistical summary we had, an absurdly large amount

df[df['Amount'] == df['Amount'].max()]

## As we can see it does not makes any sense someone buying 3 shirts for 999999, it is clearly a data entry mistake 

# the maximum transaction amount is unrealistic and is a data entry error

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date
48,1050,Customer_50,Female,23,Karnataka,Shirt,Clothing,3,999999.0,UPI,2026-07-21

In [39]:
## Let us remove this column

df.drop(index=48, inplace=True)

In [40]:
## Revalidation

df[df['Amount'] == df['Amount'].max()]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date
59,1061,Customer_61,Male,34,Gujarat,Mixer,Home,2,9357.0,NetBanking,2026-07-04

# Date Column

In [41]:
## Date Validation

df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [42]:
df['Order_Date'].dtype

dtype('<M8[ns]')

#### Creating Date features

In [43]:
df['Order_Month'] = df['Order_Date'].dt.month_name()

In [44]:
df[['Order_Date', 'Order_Month']].head()

  Order_Date Order_Month
0 2026-07-01        July
1 2026-07-02        July
2 2026-07-03        July
4 2026-07-05        July
5 2026-07-06        July

# Final Dataset Validation

In [45]:
df.shape

(51, 12)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 0 to 59
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    51 non-null     object
 1   Customer_Name  51 non-null     object
 2   Gender         51 non-null     object
 3   Age            51 non-null     int64
 4   State          51 non-null     object
 5   Product        51 non-null     object
 6   Category       51 non-null     object
 7   Orders         51 non-null     int64
 8   Amount         51 non-null     float64
 9   Payment_Mode   51 non-null     object
 10  Order_Date     51 non-null     datetime64[ns]
 11  Order_Month    51 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(8)
memory usage: 5.2+ KB

In [47]:
df.isnull().sum()

Customer_ID      0
Customer_Name    0
Gender           0
Age              0
State            0
Product          0
Category         0
Orders           0
Amount           0
Payment_Mode     0
Order_Date       0
Order_Month      0
dtype: int64

In [48]:
df.duplicated().sum()

0

In [49]:
df.describe()

             Age     Orders       Amount                     Order_Date
count  51.000000  51.000000    51.000000                             51
mean   37.117647   2.549020  5553.235294  2026-07-14 02:49:24.705882368
min    18.000000   1.000000  1274.000000            2026-07-01 00:00:00
25%    26.500000   2.000000  3740.000000            2026-07-05 12:00:00
50%    34.000000   3.000000  5521.000000            2026-07-15 00:00:00
75%    47.500000   3.500000  7507.500000            2026-07-22 00:00:00
max    62.000000   4.000000  9357.000000            2026-07-28 00:00:00
std    12.974817   1.101158  2366.032160                            NaN

In [50]:
## Saving this clean csv

df.to_csv("Clean_Data.csv", index=False)