#  Data Inspection & Cleaning

#### Initial Dataset Inspection

In [88]:
# load the dataset 

import pandas as pd 

df = pd.read_csv("Toy_Data_Cleaning_Practice.csv")

print(df)

    Customer_ID Customer_Name  Gender  Age        State Product     Category  \
0          1002    Customer_2       F   20        Delhi  Laptop  Electronics
1          1003    Customer_3       M   21           UP   Shoes     Footwear
2          1004    Customer_4       F   22  Maharashtra    Rice         Food
3          1005    Customer_5       M   23    Karnataka   Shirt     Clothing
4          1006    Customer_6       F   24      Gujarat   Mixer         Home
5          1007    Customer_7       M   25        Delhi  Laptop  Electronics
6          1008    Customer_8     NaN   26           UP   Shoes     Footwear
7          1009    Customer_9       M   27  Maharashtra    Rice         Food
8          1010   Customer_10       F   28    Karnataka   Shirt     Clothing
9          1011   Customer_11       M   29      Gujarat   Mixer         Home
10         1010   Customer_12       F   30        Delhi  Laptop  Electronics
11         1013   Customer_13       M   31           UP   Shoes     Footwear
12         1014   Customer_14       F   32  Maharashtra    Rice         Food
13         1015   Customer_15       M   33          NaN   Shirt     Clothing
14         1016   Customer_16       F   34      Gujarat   Mixer         Home
15         1017   Customer_17       M   35        Delhi  Laptop  Electronics
16         1018   Customer_18       F   36           UP   Shoes     Footwear
17         1019   Customer_19       M   37  Maharashtra    Rice         Food
18         1020   Customer_20       F   38    Karnataka   Shirt     Clothing
19         1021   Customer_21       M   39      Gujarat   Mixer         Home
20         1022   Customer_22       F   40        Delhi  Laptop  Electronics
21         1023   Customer_23       M   41           UP   Shoes     Footwear
22         1024   Customer_24       F   42  Maharashtra    Rice         Food
23         1025   Customer_25  Female   43    Karnataka   Shirt     Clothing
24         1026   Customer_26    Male   44      Gujarat   Mixer         Home
25         1027   Customer_27       M   45        Delhi  Laptop  Electronics
26         1028   Customer_28       F   46           UP   Shoes     Footwear
27         1029   Customer_29       M   47  Maharashtra    Rice         Food
28         1030   Customer_30       F   48   Maharastra   Shirt     Clothing
29         1031   Customer_31       M   49      Gujarat   Mixer         Home
30         1032   Customer_32       F   50        Delhi  Laptop  Electronics
31         1033   Customer_33       M   51           UP   Shoes     Footwear
32         1034   Customer_34       F   52  Maharashtra    Rice         Food
33         1010   Customer_35       M   53    Karnataka   Shirt     Clothing
34         1036   Customer_36       F   54      Gujarat   Mixer         Home
35         1037   Customer_37       M   55        Delhi  Laptop  Electronics
36         1038   Customer_38       F   56           UP   Shoes     Footwear
37         1039   Customer_39       M   57  Maharashtra    Rice         Food
38         1040   Customer_40       F   58    Karnataka   Shirt     Clothing
39         1041   Customer_41       M   59      Gujarat   Mixer         Home
40         1042   Customer_42       F   60        Delhi  Laptop  Electronics
41         1043   Customer_43       M   61           UP   Shoes     Footwear
42         1044   Customer_44       F   62  Maharashtra    Rice         Food
43         1045   Customer_45       M   18    Karnataka   Shirt     Clothing
44         1046   Customer_46       F   19      Gujarat   Mixer         Home
45         1047   Customer_47       M   20        Delhi  Laptop  Electronics
46         1048   Customer_48       F   21           UP   Shoes     Footwear
47         1049   Customer_49       M   22  Maharashtra    Rice         Food
48         1050   Customer_50       F   23    Karnataka   Shirt     Clothing
49         1051   Customer_51       M   24      Gujarat   Mixer         Home
50         1052   Customer_52       F   25        Delhi  Laptop  Electronics
51         1053   Customer_53       M   26           UP   Shoes     Footwear
52         1054   Customer_54       F   27  Maharashtra    Rice         Food
53         1055   Customer_55       M   28    Karnataka   Shirt     Clothing
54         1056   Customer_56       F   29      Gujarat   Mixer         Home
55         1057   Customer_57       M   30        Delhi  Laptop  Electronics
56         1058   Customer_58       F   31           UP   Shoes     Footwear
57         1059   Customer_59       M   32  Maharashtra    Rice         Food
58         1060   Customer_60       F   33    Karnataka   Shirt     Clothing
59         1061   Customer_61       M   34      Gujarat   Mixer         Home

    Orders    Amount Payment_Mode  Order_Date  Status  Notes
0        3    1274.0          UPI  2026-07-01     NaN    NaN
1        4    1411.0         Card  2026-07-02     NaN    NaN
2        1    1548.0         Cash  2026-07-03     NaN    NaN
3        2       NaN   NetBanking  2026-07-04     NaN    NaN
4        3    1822.0          UPI  2026-07-05     NaN    NaN
5        4    1959.0         Card  2026-07-06     NaN    NaN
6        1    2096.0         Cash  2026-07-07     NaN    NaN
7        2    2233.0   NetBanking  2026-07-08     NaN    NaN
8        3       NaN          UPI  2026-07-09     NaN    NaN
9        4    2507.0         Card  2026-07-10     NaN    NaN
10       1    2644.0         Cash  2026-07-11     NaN    NaN
11       2    2781.0   NetBanking  2026-07-12     NaN    NaN
12       3    2918.0          UPI  2026-07-13     NaN    NaN
13       4    3055.0         Card  2026-07-14     NaN    NaN
14       1    3192.0         Cash  2026-07-15     NaN    NaN
15       2    3329.0   NetBanking  2026-07-16     NaN    NaN
16       3    3466.0          UPI  2026-07-17     NaN    NaN
17       4    3603.0         Card  2026-07-18     NaN    NaN
18       1       NaN         Cash  2026-07-19     NaN    NaN
19       2    3877.0   NetBanking  2026-07-20     NaN    NaN
20       3    4014.0          UPI  2026-07-21     NaN    NaN
21       4    4151.0         Card  2026-07-22     NaN    NaN
22       1    4288.0         Cash  2026-07-23     NaN    NaN
23       2    4425.0   NetBanking  2026-07-24     NaN    NaN
24       3    4562.0          UPI  2026-07-25     NaN    NaN
25       4    4699.0         Card  2026-07-26     NaN    NaN
26       1    4836.0         Cash  2026-07-27     NaN    NaN
27       2    4973.0   NetBanking  2026-07-28     NaN    NaN
28       3    5110.0          UPI  2026-07-01     NaN    NaN
29       4    5247.0         Card  2026-07-02     NaN    NaN
30       1    5384.0         Cash  2026-07-03     NaN    NaN
31       2    5521.0   NetBanking  2026-07-04     NaN    NaN
32       3    5658.0          UPI  2026-07-05     NaN    NaN
33       4    5795.0         Card  2026-07-06     NaN    NaN
34       1    5932.0         Cash  2026-07-07     NaN    NaN
35       2    6069.0   NetBanking  2026-07-08     NaN    NaN
36       3    6206.0          UPI  2026-07-09     NaN    NaN
37       4    6343.0         Card  2026-07-10     NaN    NaN
38       1    -500.0         Cash  2026-07-11     NaN    NaN
39       2    6617.0   NetBanking  2026-07-12     NaN    NaN
40       3    6754.0          UPI  2026-07-13     NaN    NaN
41       4    6891.0         Card  2026-07-14     NaN    NaN
42       1    7028.0         Cash  2026-07-15     NaN    NaN
43       2    7165.0   NetBanking  2026-07-16     NaN    NaN
44       3    7302.0          UPI  2026-07-17     NaN    NaN
45       4    7439.0         Card  2026-07-18     NaN    NaN
46       1    7576.0         Cash  2026-07-19     NaN    NaN
47       2    7713.0   NetBanking  2026-07-20     NaN    NaN
48       3  999999.0          UPI  2026-07-21     NaN    NaN
49       4    7987.0         Card  2026-07-22     NaN    NaN
50       1    8124.0         Cash  2026-07-23     NaN    NaN
51       2    8261.0   NetBanking  2026-07-24     NaN    NaN
52       3    8398.0          UPI  2026-07-25     NaN    NaN
53       4    8535.0         Card  2026-07-26     NaN    NaN
54       1    8672.0         Cash  2026-07-27     NaN    NaN
55       2    8809.0   NetBanking  2026-07-28     NaN    NaN
56       3    8946.0          UPI  2026-07-01     NaN    NaN
57       4    9083.0         Card  2026-07-02     NaN    NaN
58       1    9220.0         Cash  2026-07-03     NaN    NaN
59       2    9357.0   NetBanking  2026-07-04     NaN    NaN

In [2]:
# Displaying first and last five rows 

df.head()

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
0,1002,Customer_2,F,20,Delhi,Laptop,Electronics,3,1274.0,UPI,2026-07-01,NaN,NaN
1,1003,Customer_3,M,21,UP,Shoes,Footwear,4,1411.0,Card,2026-07-02,NaN,NaN
2,1004,Customer_4,F,22,Maharashtra,Rice,Food,1,1548.0,Cash,2026-07-03,NaN,NaN
3,1005,Customer_5,M,23,Karnataka,Shirt,Clothing,2,NaN,NetBanking,2026-07-04,NaN,NaN
4,1006,Customer_6,F,24,Gujarat,Mixer,Home,3,1822.0,UPI,2026-07-05,NaN,NaN

In [3]:
df.tail()

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
55,1057,Customer_57,M,30,Delhi,Laptop,Electronics,2,8809.0,NetBanking,2026-07-28,NaN,NaN
56,1058,Customer_58,F,31,UP,Shoes,Footwear,3,8946.0,UPI,2026-07-01,NaN,NaN
57,1059,Customer_59,M,32,Maharashtra,Rice,Food,4,9083.0,Card,2026-07-02,NaN,NaN
58,1060,Customer_60,F,33,Karnataka,Shirt,Clothing,1,9220.0,Cash,2026-07-03,NaN,NaN
59,1061,Customer_61,M,34,Gujarat,Mixer,Home,2,9357.0,NetBanking,2026-07-04,NaN,NaN

In [5]:
df.shape

## Rows : 60
## Columns : 13

(60, 13)

In [6]:
df.columns

# There are 13 columns

# Identifiers : Customer_ID
# Numerical : Age, Amount, Orders
# Categorical : Customer_name, gender, state, products, category, payment_mode, order date
# Additional : status , notes

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'Product',
       'Category', 'Orders', 'Amount', 'Payment_Mode', 'Order_Date', 'Status',
       'Notes'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    60 non-null     int64
 1   Customer_Name  60 non-null     object
 2   Gender         59 non-null     object
 3   Age            60 non-null     int64
 4   State          59 non-null     object
 5   Product        60 non-null     object
 6   Category       60 non-null     object
 7   Orders         60 non-null     int64
 8   Amount         57 non-null     float64
 9   Payment_Mode   60 non-null     object
 10  Order_Date     60 non-null     object
 11  Status         0 non-null      float64
 12  Notes          0 non-null      float64
dtypes: float64(3), int64(3), object(7)
memory usage: 6.2+ KB

In [2]:
df.dtypes

Customer_ID        int64
Customer_Name     object
Gender            object
Age                int64
State             object
Product           object
Category          object
Orders             int64
Amount           float64
Payment_Mode      object
Order_Date        object
Status           float64
Notes            float64
dtype: object

In [9]:
df.describe()

## Age : There are on avergae of 36 year old contributing to sales, min age : 18 , max age : 62
## Orders  : there is 2 average qty thar is being ordred and min = 1 ,max  4
## amount avg : 22742 , -500,

       Customer_ID        Age     Orders         Amount  Status  Notes
count    60.000000  60.000000  60.000000      57.000000     0.0    0.0
mean   1031.050000  36.750000   2.500000   22742.175439     NaN    NaN
std      17.714712  12.869126   1.127469  131775.271428     NaN    NaN
min    1002.000000  18.000000   1.000000    -500.000000     NaN    NaN
25%    1015.750000  26.000000   1.750000    3329.000000     NaN    NaN
50%    1030.500000  33.500000   2.500000    5384.000000     NaN    NaN
75%    1046.250000  47.250000   3.250000    7439.000000     NaN    NaN
max    1061.000000  62.000000   4.000000  999999.000000     NaN    NaN

### Investigation til now 

##### In our Dataset
* There are 60 rows and 13 columns present
* Size : (60,13)
* Numerical Columns : Age, Orders, amount
* Categorical Columns : Customer_name, gender, state, products, category, payment_mode
* Identifiers Columns : customer_id
* Date Columns : order_date
* Unecessary columns : status , notes

* Some Future decisions
    * Status : mostly empty and null, provides no useful info for analysis ,descision : drop
    * Notes : Mostly empty and null also provides no useful info for analysis , decison : drop
    * Customer_ID : Chaneg data type from int to str , because it represents lables not numerical values

* This is a sales data set including a customers demographic information, purchasing records , over all sales, our goal is to analyze the data and extract meaningful insights to improve sales.

# Columns Categorization

# Data Cleaning

In [66]:
df.drop(columns=['Status'],inplace=True)

In [67]:
df.drop(columns=['Notes'],inplace=True)

In [85]:
## Identifier Column

df['Customer_ID'] = df['Customer_ID'].astype(str)

df['Customer_ID'].dtype

dtype('O')

In [87]:
df['Customer_ID'].duplicated().sum()

2

In [88]:
df[df['Customer_ID'].duplicated(keep=False)]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
8,1010,Customer_10,F,28,Karnataka,Shirt,Clothing,3,NaN,UPI,2026-07-09,NaN,NaN
10,1010,Customer_12,F,30,Delhi,Laptop,Electronics,1,2644.0,Cash,2026-07-11,NaN,NaN
33,1010,Customer_35,M,53,Karnataka,Shirt,Clothing,4,5795.0,Card,2026-07-06,NaN,NaN

In [89]:
df.drop_duplicates(subset=['Customer_ID'],inplace=True)

In [90]:
df['Customer_ID'].duplicated().sum()

0

In [91]:
df['Customer_ID'].isnull().sum()

0

# Categorical Columns

In [4]:
df[['Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode']].isnull().sum()

Customer_Name    0
Gender           1
State            1
Product          0
Category         0
Payment_Mode     0
dtype: int64

In [5]:
df[df[[
    'Gender',
    'State'
]].isnull().any(axis=1)]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
6,1008,Customer_8,NaN,26,UP,Shoes,Footwear,1,2096.0,Cash,2026-07-07,NaN,NaN
13,1015,Customer_15,M,33,NaN,Shirt,Clothing,4,3055.0,Card,2026-07-14,NaN,NaN

In [6]:
df[df['Gender'].isnull()]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
6,1008,Customer_8,NaN,26,UP,Shoes,Footwear,1,2096.0,Cash,2026-07-07,NaN,NaN

In [80]:
df.dropna(subset=['Gender', 'State'], inplace=True)

In [8]:
df[[
    'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
    
]].duplicated().sum()

0

In [9]:
df[['Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode']].isnull().sum()

Customer_Name    0
Gender           0
State            0
Product          0
Category         0
Payment_Mode     0
dtype: int64

In [10]:
df['Gender'].value_counts()

Gender
F         28
M         28
Female     1
Male       1
Name: count, dtype: int64

In [ ]:
## Category Validation — Consistency & Standardization

categorical_cols = [
        'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

Customer_Name
['Customer_2' 'Customer_3' 'Customer_4' 'Customer_5' 'Customer_6'
 'Customer_7' 'Customer_9' 'Customer_10' 'Customer_11' 'Customer_12'
 'Customer_13' 'Customer_14' 'Customer_16' 'Customer_17' 'Customer_18'
 'Customer_19' 'Customer_20' 'Customer_21' 'Customer_22' 'Customer_23'
 'Customer_24' 'Customer_25' 'Customer_26' 'Customer_27' 'Customer_28'
 'Customer_29' 'Customer_30' 'Customer_31' 'Customer_32' 'Customer_33'
 'Customer_34' 'Customer_35' 'Customer_36' 'Customer_37' 'Customer_38'
 'Customer_39' 'Customer_40' 'Customer_41' 'Customer_42' 'Customer_43'
 'Customer_44' 'Customer_45' 'Customer_46' 'Customer_47' 'Customer_48'
 'Customer_49' 'Customer_50' 'Customer_51' 'Customer_52' 'Customer_53'
 'Customer_54' 'Customer_55' 'Customer_56' 'Customer_57' 'Customer_58'
 'Customer_59' 'Customer_60' 'Customer_61']

Gender
['F' 'M' 'Female' 'Male']

State
['Delhi' 'UP' 'Maharashtra' 'Karnataka' 'Gujarat' 'Maharastra']

Product
['Laptop' 'Shoes' 'Rice' 'Shirt' 'Mixer']

Category
['Electronics' 'Footwear' 'Food' 'Clothing' 'Home']

Payment_Mode
['UPI' 'Card' 'Cash' 'NetBanking']

In [13]:
df['Gender'] = df['Gender'].replace(
    {
        'M' : 'Male',
        'F' : 'Female'
    }
)

In [18]:
df['State'] = df['State'].replace(
    {
        'Maharastra' : 'Maharashtra'
    }
)

In [19]:
categorical_cols = [
        'Customer_Name',
    'Gender',
    'State',
    'Product',
    'Category',
    'Payment_Mode'
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

Customer_Name
['Customer_2' 'Customer_3' 'Customer_4' 'Customer_5' 'Customer_6'
 'Customer_7' 'Customer_9' 'Customer_10' 'Customer_11' 'Customer_12'
 'Customer_13' 'Customer_14' 'Customer_16' 'Customer_17' 'Customer_18'
 'Customer_19' 'Customer_20' 'Customer_21' 'Customer_22' 'Customer_23'
 'Customer_24' 'Customer_25' 'Customer_26' 'Customer_27' 'Customer_28'
 'Customer_29' 'Customer_30' 'Customer_31' 'Customer_32' 'Customer_33'
 'Customer_34' 'Customer_35' 'Customer_36' 'Customer_37' 'Customer_38'
 'Customer_39' 'Customer_40' 'Customer_41' 'Customer_42' 'Customer_43'
 'Customer_44' 'Customer_45' 'Customer_46' 'Customer_47' 'Customer_48'
 'Customer_49' 'Customer_50' 'Customer_51' 'Customer_52' 'Customer_53'
 'Customer_54' 'Customer_55' 'Customer_56' 'Customer_57' 'Customer_58'
 'Customer_59' 'Customer_60' 'Customer_61']

Gender
['Female' 'Male']

State
['Delhi' 'UP' 'Maharashtra' 'Karnataka' 'Gujarat']

Product
['Laptop' 'Shoes' 'Rice' 'Shirt' 'Mixer']

Category
['Electronics' 'Footwear' 'Food' 'Clothing' 'Home']

Payment_Mode
['UPI' 'Card' 'Cash' 'NetBanking']

# Numerical Columns Validation 

---

### Validation Checklist

For **each numerical column**:

- [ ]  Missing values
- [ ]  Correct datatype
- [ ]  Minimum value
- [ ]  Maximum value
- [ ]  Mean
- [ ]  Median
- [ ]  Negative values
- [ ]  Impossible values
- [ ]  Outliers
- [ ]  Zero values

In [27]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].info()

df[numerical_cols].describe()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 59
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Amount  55 non-null     float64
 1   Age     58 non-null     int64
 2   Orders  58 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 1.8 KB

              Amount        Age     Orders
count      55.000000  58.000000  58.000000
mean    23475.509091  37.000000   2.500000
std    134135.159428  13.003373   1.112134
min      -500.000000  18.000000   1.000000
25%      3534.500000  26.250000   2.000000
50%      5521.000000  34.000000   2.500000
75%      7507.500000  47.750000   3.000000
max    999999.000000  62.000000   4.000000

In [26]:
## Handling Nulls

numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].isnull().sum()

Amount    3
Age       0
Orders    0
dtype: int64

In [86]:
df = df.dropna(subset=['Amount'], inplace=True)

In [40]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].isnull().sum()

Amount    0
Age       0
Orders    0
dtype: int64

In [42]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].duplicated().sum()

0

In [37]:
numerical_cols = ['Amount','Age','Orders']

df[numerical_cols].agg(['min','max'])

       Amount  Age  Orders
min    -500.0   18       1
max  999999.0   62       4

In [54]:
df[df['Amount']<0]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, State, Product, Category, Orders, Amount, Payment_Mode, Order_Date, Status, Notes]
Index: []

In [52]:
## removing row with negative amount

df = df.drop(index=38)

In [56]:
df[df['Amount'] == df['Amount'].max()]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
48,1050,Customer_50,F,23,Karnataka,Shirt,Clothing,3,999999.0,UPI,2026-07-21,NaN,NaN

In [57]:
df = df.drop(index=48)

In [61]:
df[df['Amount'] == df['Amount'].max()]

,Customer_ID,Customer_Name,Gender,Age,State,Product,Category,Orders,Amount,Payment_Mode,Order_Date,Status,Notes
59,1061,Customer_61,M,34,Gujarat,Mixer,Home,2,9357.0,NetBanking,2026-07-04,NaN,NaN

In [70]:
df['Order_Date'].head()

0    2026-07-01
1    2026-07-02
2    2026-07-03
3    2026-07-04
4    2026-07-05
Name: Order_Date, dtype: object

# Step 7 — Final Dataset Validation

### Checklist

- [ ]  Dataset shape
- [ ]  Column names
- [ ]  Data types
- [ ]  Missing values
- [ ]  Duplicate rows
- [ ]  Duplicate identifiers
- [ ]  Category consistency
- [ ]  Numerical summary

In [62]:
df.shape

(58, 13)

In [68]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'Product',
       'Category', 'Orders', 'Amount', 'Payment_Mode', 'Order_Date'],
      dtype='object')

In [89]:
df.isnull().sum()

Customer_ID       0
Customer_Name     0
Gender            1
Age               0
State             1
Product           0
Category          0
Orders            0
Amount            3
Payment_Mode      0
Order_Date        0
Status           60
Notes            60
dtype: int64